name: 🐞 Bug or error report
description: Report a suspected bug or error.
labels: ['Needs: Triage :mag:', 'type:bug-suspected']

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug **only**.
      
      - All bug reports are welcome - we want to fix them!
      - This repo is maintained by volunteers. Please be courteous and patient as responses can take time. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
      - We accept pull requests. If you know how to fix it - go ahead! Fork the repo and submit a PR and we can take a look at it. 

      Please provide the following details about the issue you encountered. 

- type: textarea
  id: description
  attributes:
    label: Description
    description: Provide a short description of the issue you are facing.
    placeholder: Tell us in brief what is happening
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    description: How do you reproduce this? Please provide as much step-by-step detail as possible.
    value: |
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: What did you expect to happen when the reproduce steps are followed?
    placeholder: Tell us what you expected to see!
  validations:
    required: true
